enum TransactionType { rent, sell }

enum PropertyType { house, villa, apartment }

class Building {
  final String name;
  final TransactionType transactionType;
  final PropertyType propertyType;
  final String location;
  final String imageAsset;
  final int price;
  final int beds;
  final int baths;
  final int garages;
  final int sqm;

  const Building({
    required this.name,
    required this.transactionType,
    required this.propertyType,
    required this.location,
    required this.imageAsset,
    required this.price,
    required this.beds,
    required this.baths,
    required this.garages,
    required this.sqm,
  });
}

final buildingLists = [
  Building(
    name: 'Modern Family House',
    transactionType: TransactionType.sell,
    propertyType: PropertyType.house,
    location: 'Jakarta Selatan',
    imageAsset: '',
    price: 2500000000,
    beds: 4,
    baths: 3,
    garages: 2,
    sqm: 180,
  ),
  Building(
    name: 'Urban Minimalist House',
    transactionType: TransactionType.sell,
    propertyType: PropertyType.house,
    location: 'Bandung',
    imageAsset: '',
    price: 1800000000,
    beds: 3,
    baths: 2,
    garages: 1,
    sqm: 140,
  ),
  Building(
    name: 'City View Apartment',
    transactionType: TransactionType.rent,
    propertyType: PropertyType.apartment,
    location: 'Jakarta Pusat',
    imageAsset: '',
    price: 8500000,
    beds: 2,
    baths: 1,
    garages: 1,
    sqm: 75,
  ),
  Building(
    name: 'Compact Studio Apartment',
    transactionType: TransactionType.rent,
    propertyType: PropertyType.apartment,
    location: 'Bekasi',
    imageAsset: '',
    price: 4500000,
    beds: 1,
    baths: 1,
    garages: 0,
    sqm: 40,
  ),
  Building(
    name: 'Luxury Tropical Villa',
    transactionType: TransactionType.sell,
    propertyType: PropertyType.villa,
    location: 'Bali',
    imageAsset: '',
    price: 6200000000,
    beds: 5,
    baths: 4,
    garages: 2,
    sqm: 350,
  ),
  Building(
    name: 'Beachfront Villa',
    transactionType: TransactionType.rent,
    propertyType: PropertyType.villa,
    location: 'Lombok',
    imageAsset: '',
    price: 45000000,
    beds: 4,
    baths: 4,
    garages: 2,
    sqm: 300,
  ),
  Building(
    name: 'Suburban Comfort House',
    transactionType: TransactionType.sell,
    propertyType: PropertyType.house,
    location: 'Depok',
    imageAsset: '',
    price: 1300000000,
    beds: 3,
    baths: 2,
    garages: 1,
    sqm: 130,
  ),
  Building(
    name: 'Green Living Residence',
    transactionType: TransactionType.sell,
    propertyType: PropertyType.house,
    location: 'Bogor',
    imageAsset: '',
    price: 1450000000,
    beds: 3,
    baths: 2,
    garages: 1,
    sqm: 150,
  ),
  Building(
    name: 'Skyline Apartment',
    transactionType: TransactionType.sell,
    propertyType: PropertyType.apartment,
    location: 'Surabaya',
    imageAsset: '',
    price: 2100000000,
    beds: 2,
    baths: 2,
    garages: 1,
    sqm: 90,
  ),
  Building(
    name: 'Central Business Apartment',
    transactionType: TransactionType.rent,
    propertyType: PropertyType.apartment,
    location: 'Jakarta Barat',
    imageAsset: '',
    price: 9500000,
    beds: 2,
    baths: 1,
    garages: 1,
    sqm: 80,
  ),
  Building(
    name: 'Elegant Classic House',
    transactionType: TransactionType.sell,
    propertyType: PropertyType.house,
    location: 'Yogyakarta',
    imageAsset: '',
    price: 1650000000,
    beds: 4,
    baths: 3,
    garages: 2,
    sqm: 200,
  ),
  Building(
    name: 'Modern Cluster House',
    transactionType: TransactionType.rent,
    propertyType: PropertyType.house,
    location: 'Tangerang',
    imageAsset: '',
    price: 12000000,
    beds: 3,
    baths: 2,
    garages: 1,
    sqm: 120,
  ),
  Building(
    name: 'Private Pool Villa',
    transactionType: TransactionType.sell,
    propertyType: PropertyType.villa,
    location: 'Ubud',
    imageAsset: '',
    price: 7200000000,
    beds: 6,
    baths: 5,
    garages: 2,
    sqm: 420,
  ),
  Building(
    name: 'Cozy Hillside Villa',
    transactionType: TransactionType.rent,
    propertyType: PropertyType.villa,
    location: 'Puncak',
    imageAsset: '',
    price: 38000000,
    beds: 4,
    baths: 3,
    garages: 1,
    sqm: 280,
  ),
  Building(
    name: 'Affordable City Apartment',
    transactionType: TransactionType.sell,
    propertyType: PropertyType.apartment,
    location: 'Malang',
    imageAsset: '',
    price: 980000000,
    beds: 2,
    baths: 1,
    garages: 0,
    sqm: 65,
  ),
  Building(
    name: 'Premium Downtown Apartment',
    transactionType: TransactionType.rent,
    propertyType: PropertyType.apartment,
    location: 'Jakarta Selatan',
    imageAsset: '',
    price: 12500000,
    beds: 3,
    baths: 2,
    garages: 1,
    sqm: 110,
  ),
  Building(
    name: 'Family Friendly House',
    transactionType: TransactionType.sell,
    propertyType: PropertyType.house,
    location: 'Semarang',
    imageAsset: '',
    price: 1500000000,
    beds: 4,
    baths: 3,
    garages: 2,
    sqm: 170,
  ),
  Building(
    name: 'Quiet Residential House',
    transactionType: TransactionType.rent,
    propertyType: PropertyType.house,
    location: 'Solo',
    imageAsset: '',
    price: 9000000,
    beds: 3,
    baths: 2,
    garages: 1,
    sqm: 125,
  ),
  Building(
    name: 'Ocean View Villa',
    transactionType: TransactionType.sell,
    propertyType: PropertyType.villa,
    location: 'Nusa Dua',
    imageAsset: '',
    price: 8800000000,
    beds: 5,
    baths: 5,
    garages: 2,
    sqm: 450,
  ),
  Building(
    name: 'City Starter Apartment',
    transactionType: TransactionType.rent,
    propertyType: PropertyType.apartment,
    location: 'Cibubur',
    imageAsset: '',
    price: 5200000,
    beds: 1,
    baths: 1,
    garages: 0,
    sqm: 42,
  ),
];
